# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffce8ca19f1078e0ae726a34fc8fd25382150239d0531fe08531ced29221c5a5d1df41bb205d2914af4911bbbbc74eda18c838c9c20527ea0e9b762ced3c13db

test:
  secret_key_base: 90e63cd7f1a8d373471b5ba21d17958ebfd3ca8844a6bb59692812529fba6e7472beaf11b12934e72cca805d5e9ee2a03303d8dfdde5c9a1eb9cbca005d4de11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
